### ISSUE TITLE
[Demo] Wrong set of seedpoint for cv2.floodFill

### ISSUE THREAD

**Issue by frgfm** [jfzhang95/DeepGrabCut-PyTorch#4]
Hi there,

Thanks for this implementation! 
I ran into a small problem running the demo: the `cv2.floodFill` was throwing errors saying the seedpoint had wrong values. Investigating a bit, I wonder if this section below
https://github.com/jfzhang95/DeepGrabCut-PyTorch/blob/master/demo.py#L97-L100
should not be commented.

Since left, right, up, down are used to put the seedpoint, if you leave this section uncommented (and that your monitor has more than twice the amount of pixels than the displayed image), opencv throws the mentioned error:
```
cv2.error: OpenCV(3.4.5) /io/opencv/modules/imgproc/src/floodfill.cpp:509: error: (-211:One of arguments' values is out of range) Seed point is outside of image in function 'floodFill'
```
Commenting the section fixes the error as the seedpoint changes from coordinates of 1000+ pixels down back to image dimensions:
![dgc_fix](https://user-images.githubusercontent.com/26927750/57859537-6febe680-77f3-11e9-85b7-778d4d4d9488.png)

I'm unsure about how others managed to run the demo without commenting it though.

**Comment by frgfm** [comment]
And this line needs to be commented as well: https://github.com/jfzhang95/DeepGrabCut-PyTorch/blob/master/demo.py#L107
so that the user drawing is actually taken as input of `cv2.floodFill`

Below the result, after commenting also this line as well, with almost the same user input:
![dgc_fix2](https://user-images.githubusercontent.com/26927750/57861729-6bc1c800-77f7-11e9-9ada-85868727a459.png)

**Comment by jfzhang95** [comment]
Maybe the problem you mentioned is caused by different opencv version.

**Comment by frgfm** [comment]
Well, I thought so in the beginning but I don't see how:
these very lines https://github.com/jfzhang95/DeepGrabCut-PyTorch/blob/master/demo.py#L97-L100 are setting `left`, `right`, `up`, and `down` to either 0 or the size of the monitor

Thus later when calling `cv2.floodFill` with seed point at `(int((left + right) / 2), int((up + down) / 2))` there is an issue. If you comment it, the 4 values remain the extreme values of the shape drawn by the user, which is correct.

But maybe it's a versioning issue indeed: if you run `left = 0xFFF; print(left)`, which value do you get? (In my case it's 4095)

**Comment by pkjplayer** [comment]
Hello, I met the same problem as you, how do you solve it

**Comment by pkjplayer** [comment]
ok, i know, press "S", start drawing circle,and then call function interactive_drawing,and then press space

**Comment by frgfm** [comment]
Hey @pkjplayer,
I commented the sections mentioned above to get it to work properly and in my case, everything's fine now! Did you have to make modifications to get it working or was it just key mapping issues?

**Comment by pkjplayer** [comment]
there is noting wrong，the reason of this issue is the wrong operation when running your code


 
---Original---

**Comment by frgfm** [comment]
@pkjplayer my bad, I misread what you wrote in the first place!
I'll try your suggestion and keep you posted if that solves it

**Comment by frgfm** [comment]
Hi @pkjplayer 
I tried, and pressing space works perfectly! The suggestion I made earlier gives the same result without pressing the key. Good catch anyway, I'll close the issue
