### ISSUE TITLE
How to get past drawing stage?

### ISSUE THREAD

**Issue by joshmyersdean** [jfzhang95/DeepGrabCut-PyTorch#6]
I can draw a box around an object in the demo but then nothing happens.

**Comment by tpcmi** [comment]
Press space and wait 😃

**Comment by yuki4ghub15** [comment]
Hi there, After circle draw, I Pressed space and waited but nothing happening. can you tell me  torch version or other package version

**Comment by tpcmi** [comment]
> Hi there, After circle draw, I Pressed space and waited but nothing happening. can you tell me torch version or other package version

I'm not the code writer, I just use it and press space work for me....

**Comment by uestcLZX** [comment]
> 
> 
> > Hi there, After circle draw, I Pressed space and waited but nothing happening. can you tell me torch version or other package version
> 
> I'm not the code writer, I just use it and press space work for me....

How long did it take you after pressing  space and showing the label?Thanks

**Comment by uestcLZX** [comment]
> 
> 
> Hi there, After circle draw, I Pressed space and waited but nothing happening. can you tell me torch version or other package version

Hi ,have you solved this problem?Did it worked?

**Comment by tpcmi** [comment]
two or three sec



发自我的iPhone


------------------ Original ------------------

**Comment by uestcLZX** [comment]
> 
> two or three sec 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: uestcLZX <notifications@github.com&gt; Date: Mon,Jul 6,2020 11:28 AM To: jfzhang95/DeepGrabCut-PyTorch <DeepGrabCut-PyTorch@noreply.github.com&gt; Cc: tpcmi <724801800@qq.com&gt;, Comment <comment@noreply.github.com&gt; Subject: Re: [jfzhang95/DeepGrabCut-PyTorch] How to get past drawing stage? (#6)

请问你的python是3.5还是3.6/3.7？我的是3.6，但是敲空格后很久没反应

**Comment by jiunyen-ching** [comment]
@uestcLZX In case you're still interested, try these steps and see if it works for you:

1. Run `python demo.py`
2. When window appears, press "s"
3. Draw circle
4. Press spacebar and wait for 2 -3 seconds

You should be able to see the segmentation map now. To obtain a new segmentation map without closing the window, repeat Steps 2 - 4.
